#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++ -std=c++11
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions -lpthread 
RESINC = 
LIBDIR = 
LIB = /usr/src/gtest/libgtest.a -lpthread 
LDFLAGS =

INC_DEBUG = $(INC) -Iinclude
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/CS4227_Project

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/CS4227_Project

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/main.o $(OBJDIR_DEBUG)/src/TestEnemyFactory.o $(OBJDIR_DEBUG)/src/TestAchievementSystem.o $(OBJDIR_DEBUG)/src/SoundSystem.o $(OBJDIR_DEBUG)/src/RobotEnemy.o $(OBJDIR_DEBUG)/src/Player.o $(OBJDIR_DEBUG)/src/GameEvent.o $(OBJDIR_DEBUG)/src/EnemyFactory.o $(OBJDIR_DEBUG)/src/AchievementSystem.o $(OBJDIR_DEBUG)/src/Achievement.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/main.o $(OBJDIR_RELEASE)/src/TestEnemyFactory.o $(OBJDIR_RELEASE)/src/TestAchievementSystem.o $(OBJDIR_RELEASE)/src/SoundSystem.o $(OBJDIR_RELEASE)/src/RobotEnemy.o $(OBJDIR_RELEASE)/src/Player.o $(OBJDIR_RELEASE)/src/GameEvent.o $(OBJDIR_RELEASE)/src/EnemyFactory.o $(OBJDIR_RELEASE)/src/AchievementSystem.o $(OBJDIR_RELEASE)/src/Achievement.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.cpp -o $(OBJDIR_DEBUG)/src/main.o

$(OBJDIR_DEBUG)/src/TestEnemyFactory.o: src/TestEnemyFactory.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/TestEnemyFactory.cpp -o $(OBJDIR_DEBUG)/src/TestEnemyFactory.o

$(OBJDIR_DEBUG)/src/TestAchievementSystem.o: src/TestAchievementSystem.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/TestAchievementSystem.cpp -o $(OBJDIR_DEBUG)/src/TestAchievementSystem.o

$(OBJDIR_DEBUG)/src/SoundSystem.o: src/SoundSystem.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SoundSystem.cpp -o $(OBJDIR_DEBUG)/src/SoundSystem.o

$(OBJDIR_DEBUG)/src/RobotEnemy.o: src/RobotEnemy.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/RobotEnemy.cpp -o $(OBJDIR_DEBUG)/src/RobotEnemy.o

$(OBJDIR_DEBUG)/src/Player.o: src/Player.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Player.cpp -o $(OBJDIR_DEBUG)/src/Player.o

$(OBJDIR_DEBUG)/src/GameEvent.o: src/GameEvent.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/GameEvent.cpp -o $(OBJDIR_DEBUG)/src/GameEvent.o

$(OBJDIR_DEBUG)/src/EnemyFactory.o: src/EnemyFactory.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/EnemyFactory.cpp -o $(OBJDIR_DEBUG)/src/EnemyFactory.o

$(OBJDIR_DEBUG)/src/AchievementSystem.o: src/AchievementSystem.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/AchievementSystem.cpp -o $(OBJDIR_DEBUG)/src/AchievementSystem.o

$(OBJDIR_DEBUG)/src/Achievement.o: src/Achievement.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Achievement.cpp -o $(OBJDIR_DEBUG)/src/Achievement.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.o

$(OBJDIR_RELEASE)/src/TestEnemyFactory.o: src/TestEnemyFactory.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/TestEnemyFactory.cpp -o $(OBJDIR_RELEASE)/src/TestEnemyFactory.o

$(OBJDIR_RELEASE)/src/TestAchievementSystem.o: src/TestAchievementSystem.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/TestAchievementSystem.cpp -o $(OBJDIR_RELEASE)/src/TestAchievementSystem.o

$(OBJDIR_RELEASE)/src/SoundSystem.o: src/SoundSystem.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SoundSystem.cpp -o $(OBJDIR_RELEASE)/src/SoundSystem.o

$(OBJDIR_RELEASE)/src/RobotEnemy.o: src/RobotEnemy.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/RobotEnemy.cpp -o $(OBJDIR_RELEASE)/src/RobotEnemy.o

$(OBJDIR_RELEASE)/src/Player.o: src/Player.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Player.cpp -o $(OBJDIR_RELEASE)/src/Player.o

$(OBJDIR_RELEASE)/src/GameEvent.o: src/GameEvent.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/GameEvent.cpp -o $(OBJDIR_RELEASE)/src/GameEvent.o

$(OBJDIR_RELEASE)/src/EnemyFactory.o: src/EnemyFactory.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/EnemyFactory.cpp -o $(OBJDIR_RELEASE)/src/EnemyFactory.o

$(OBJDIR_RELEASE)/src/AchievementSystem.o: src/AchievementSystem.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/AchievementSystem.cpp -o $(OBJDIR_RELEASE)/src/AchievementSystem.o

$(OBJDIR_RELEASE)/src/Achievement.o: src/Achievement.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Achievement.cpp -o $(OBJDIR_RELEASE)/src/Achievement.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

